// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_HAPTICFRAME_NULLSPACE_HAPTICFILES_H_
#define FLATBUFFERS_GENERATED_HAPTICFRAME_NULLSPACE_HAPTICFILES_H_

#include "flatbuffers/flatbuffers.h"

#include "HapticEffect_generated.h"
#include "Sequence_generated.h"

namespace NullSpace {
namespace HapticFiles {

struct HapticFrame;

struct HapticFrame FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_TIME = 4,
    VT_SEQUENCE = 6,
    VT_AREA = 8
  };
  float time() const { return GetField<float>(VT_TIME, 0.0f); }
  const NullSpace::HapticFiles::Sequence *sequence() const { return GetPointer<const NullSpace::HapticFiles::Sequence *>(VT_SEQUENCE); }
  const flatbuffers::String *area() const { return GetPointer<const flatbuffers::String *>(VT_AREA); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_TIME) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_SEQUENCE) &&
           verifier.VerifyTable(sequence()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_AREA) &&
           verifier.Verify(area()) &&
           verifier.EndTable();
  }
};

struct HapticFrameBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_time(float time) { fbb_.AddElement<float>(HapticFrame::VT_TIME, time, 0.0f); }
  void add_sequence(flatbuffers::Offset<NullSpace::HapticFiles::Sequence> sequence) { fbb_.AddOffset(HapticFrame::VT_SEQUENCE, sequence); }
  void add_area(flatbuffers::Offset<flatbuffers::String> area) { fbb_.AddOffset(HapticFrame::VT_AREA, area); }
  HapticFrameBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  HapticFrameBuilder &operator=(const HapticFrameBuilder &);
  flatbuffers::Offset<HapticFrame> Finish() {
    auto o = flatbuffers::Offset<HapticFrame>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<HapticFrame> CreateHapticFrame(flatbuffers::FlatBufferBuilder &_fbb,
    float time = 0.0f,
    flatbuffers::Offset<NullSpace::HapticFiles::Sequence> sequence = 0,
    flatbuffers::Offset<flatbuffers::String> area = 0) {
  HapticFrameBuilder builder_(_fbb);
  builder_.add_area(area);
  builder_.add_sequence(sequence);
  builder_.add_time(time);
  return builder_.Finish();
}

inline flatbuffers::Offset<HapticFrame> CreateHapticFrameDirect(flatbuffers::FlatBufferBuilder &_fbb,
    float time = 0.0f,
    flatbuffers::Offset<NullSpace::HapticFiles::Sequence> sequence = 0,
    const char *area = nullptr) {
  return CreateHapticFrame(_fbb, time, sequence, area ? _fbb.CreateString(area) : 0);
}

inline const NullSpace::HapticFiles::HapticFrame *GetHapticFrame(const void *buf) {
  return flatbuffers::GetRoot<NullSpace::HapticFiles::HapticFrame>(buf);
}

inline bool VerifyHapticFrameBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<NullSpace::HapticFiles::HapticFrame>(nullptr);
}

inline void FinishHapticFrameBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<NullSpace::HapticFiles::HapticFrame> root) {
  fbb.Finish(root);
}

}  // namespace HapticFiles
}  // namespace NullSpace

#endif  // FLATBUFFERS_GENERATED_HAPTICFRAME_NULLSPACE_HAPTICFILES_H_
