// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_MIXEDSEQUENCE_NULLSPACE_HAPTICFILES_MIXED_H_
#define FLATBUFFERS_GENERATED_MIXEDSEQUENCE_NULLSPACE_HAPTICFILES_MIXED_H_

#include "flatbuffers/flatbuffers.h"

#include "HapticEffect_generated.h"

namespace NullSpace {
namespace HapticFiles {
namespace Mixed {

struct ListOfHapticEffects;

struct SeqRef;

struct Sequence;

enum EffectValuesOrNameReference {
  EffectValuesOrNameReference_NONE = 0,
  EffectValuesOrNameReference_ListOfHapticEffects = 1,
  EffectValuesOrNameReference_SeqRef = 2,
  EffectValuesOrNameReference_MIN = EffectValuesOrNameReference_NONE,
  EffectValuesOrNameReference_MAX = EffectValuesOrNameReference_SeqRef
};

inline const char **EnumNamesEffectValuesOrNameReference() {
  static const char *names[] = { "NONE", "ListOfHapticEffects", "SeqRef", nullptr };
  return names;
}

inline const char *EnumNameEffectValuesOrNameReference(EffectValuesOrNameReference e) { return EnumNamesEffectValuesOrNameReference()[static_cast<int>(e)]; }

template<typename T> struct EffectValuesOrNameReferenceTraits {
  static const EffectValuesOrNameReference enum_value = EffectValuesOrNameReference_NONE;
};

template<> struct EffectValuesOrNameReferenceTraits<ListOfHapticEffects> {
  static const EffectValuesOrNameReference enum_value = EffectValuesOrNameReference_ListOfHapticEffects;
};

template<> struct EffectValuesOrNameReferenceTraits<SeqRef> {
  static const EffectValuesOrNameReference enum_value = EffectValuesOrNameReference_SeqRef;
};

inline bool VerifyEffectValuesOrNameReference(flatbuffers::Verifier &verifier, const void *union_obj, EffectValuesOrNameReference type);

struct ListOfHapticEffects FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ITEMS = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<NullSpace::HapticFiles::HapticEffect>> *items() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<NullSpace::HapticFiles::HapticEffect>> *>(VT_ITEMS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_ITEMS) &&
           verifier.Verify(items()) &&
           verifier.VerifyVectorOfTables(items()) &&
           verifier.EndTable();
  }
};

struct ListOfHapticEffectsBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_items(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<NullSpace::HapticFiles::HapticEffect>>> items) { fbb_.AddOffset(ListOfHapticEffects::VT_ITEMS, items); }
  ListOfHapticEffectsBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  ListOfHapticEffectsBuilder &operator=(const ListOfHapticEffectsBuilder &);
  flatbuffers::Offset<ListOfHapticEffects> Finish() {
    auto o = flatbuffers::Offset<ListOfHapticEffects>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<ListOfHapticEffects> CreateListOfHapticEffects(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<NullSpace::HapticFiles::HapticEffect>>> items = 0) {
  ListOfHapticEffectsBuilder builder_(_fbb);
  builder_.add_items(items);
  return builder_.Finish();
}

inline flatbuffers::Offset<ListOfHapticEffects> CreateListOfHapticEffectsDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<NullSpace::HapticFiles::HapticEffect>> *items = nullptr) {
  return CreateListOfHapticEffects(_fbb, items ? _fbb.CreateVector<flatbuffers::Offset<NullSpace::HapticFiles::HapticEffect>>(*items) : 0);
}

struct SeqRef FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_SYMBOL = 4
  };
  const flatbuffers::String *symbol() const { return GetPointer<const flatbuffers::String *>(VT_SYMBOL); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_SYMBOL) &&
           verifier.Verify(symbol()) &&
           verifier.EndTable();
  }
};

struct SeqRefBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_symbol(flatbuffers::Offset<flatbuffers::String> symbol) { fbb_.AddOffset(SeqRef::VT_SYMBOL, symbol); }
  SeqRefBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  SeqRefBuilder &operator=(const SeqRefBuilder &);
  flatbuffers::Offset<SeqRef> Finish() {
    auto o = flatbuffers::Offset<SeqRef>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<SeqRef> CreateSeqRef(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> symbol = 0) {
  SeqRefBuilder builder_(_fbb);
  builder_.add_symbol(symbol);
  return builder_.Finish();
}

inline flatbuffers::Offset<SeqRef> CreateSeqRefDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const char *symbol = nullptr) {
  return CreateSeqRef(_fbb, symbol ? _fbb.CreateString(symbol) : 0);
}

struct Sequence FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_LOCATION = 4,
    VT_EFFECT_TYPE = 6,
    VT_EFFECT = 8
  };
  uint32_t location() const { return GetField<uint32_t>(VT_LOCATION, 0); }
  EffectValuesOrNameReference effect_type() const { return static_cast<EffectValuesOrNameReference>(GetField<uint8_t>(VT_EFFECT_TYPE, 0)); }
  const void *effect() const { return GetPointer<const void *>(VT_EFFECT); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_LOCATION) &&
           VerifyField<uint8_t>(verifier, VT_EFFECT_TYPE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_EFFECT) &&
           VerifyEffectValuesOrNameReference(verifier, effect(), effect_type()) &&
           verifier.EndTable();
  }
};

struct SequenceBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_location(uint32_t location) { fbb_.AddElement<uint32_t>(Sequence::VT_LOCATION, location, 0); }
  void add_effect_type(EffectValuesOrNameReference effect_type) { fbb_.AddElement<uint8_t>(Sequence::VT_EFFECT_TYPE, static_cast<uint8_t>(effect_type), 0); }
  void add_effect(flatbuffers::Offset<void> effect) { fbb_.AddOffset(Sequence::VT_EFFECT, effect); }
  SequenceBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  SequenceBuilder &operator=(const SequenceBuilder &);
  flatbuffers::Offset<Sequence> Finish() {
    auto o = flatbuffers::Offset<Sequence>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<Sequence> CreateSequence(flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t location = 0,
    EffectValuesOrNameReference effect_type = EffectValuesOrNameReference_NONE,
    flatbuffers::Offset<void> effect = 0) {
  SequenceBuilder builder_(_fbb);
  builder_.add_effect(effect);
  builder_.add_location(location);
  builder_.add_effect_type(effect_type);
  return builder_.Finish();
}

inline bool VerifyEffectValuesOrNameReference(flatbuffers::Verifier &verifier, const void *union_obj, EffectValuesOrNameReference type) {
  switch (type) {
    case EffectValuesOrNameReference_NONE: return true;
    case EffectValuesOrNameReference_ListOfHapticEffects: return verifier.VerifyTable(reinterpret_cast<const ListOfHapticEffects *>(union_obj));
    case EffectValuesOrNameReference_SeqRef: return verifier.VerifyTable(reinterpret_cast<const SeqRef *>(union_obj));
    default: return false;
  }
}

inline const NullSpace::HapticFiles::Mixed::Sequence *GetSequence(const void *buf) {
  return flatbuffers::GetRoot<NullSpace::HapticFiles::Mixed::Sequence>(buf);
}

inline bool VerifySequenceBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<NullSpace::HapticFiles::Mixed::Sequence>(nullptr);
}

inline void FinishSequenceBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<NullSpace::HapticFiles::Mixed::Sequence> root) {
  fbb.Finish(root);
}

}  // namespace Mixed
}  // namespace HapticFiles
}  // namespace NullSpace

#endif  // FLATBUFFERS_GENERATED_MIXEDSEQUENCE_NULLSPACE_HAPTICFILES_MIXED_H_
