// automatically generated by the FlatBuffers compiler, do not modify

namespace NullSpace.HapticFiles
{

public enum NodeType : short
{
 Effect = 0,
 Sequence = 1,
 Pattern = 2,
 Experience = 3,
};


}
