// automatically generated by the FlatBuffers compiler, do not modify

namespace NullSpace.HapticFiles
{

public enum EngineCommand : short
{
 NO_COMMAND = 0,
 PLAY_ALL = 1,
 PAUSE_ALL = 2,
 CLEAR_ALL = 3,
 ENABLE_TRACKING = 4,
 DISABLE_TRACKING = 5,
};


}
