// automatically generated by the FlatBuffers compiler, do not modify

namespace NullSpace.Events
{

using System;
using FlatBuffers;

public struct BasicHapticEvent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static BasicHapticEvent GetRootAsBasicHapticEvent(ByteBuffer _bb) { return GetRootAsBasicHapticEvent(_bb, new BasicHapticEvent()); }
  public static BasicHapticEvent GetRootAsBasicHapticEvent(ByteBuffer _bb, BasicHapticEvent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public BasicHapticEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Time { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Strength { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Duration { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public uint Area { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Effect { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetEffectBytes() { return __p.__vector_as_arraysegment(12); }

  public static Offset<BasicHapticEvent> CreateBasicHapticEvent(FlatBufferBuilder builder,
      float time = 0.0f,
      float strength = 0.0f,
      float duration = 0.0f,
      uint area = 0,
      StringOffset effectOffset = default(StringOffset)) {
    builder.StartObject(5);
    BasicHapticEvent.AddEffect(builder, effectOffset);
    BasicHapticEvent.AddArea(builder, area);
    BasicHapticEvent.AddDuration(builder, duration);
    BasicHapticEvent.AddStrength(builder, strength);
    BasicHapticEvent.AddTime(builder, time);
    return BasicHapticEvent.EndBasicHapticEvent(builder);
  }

  public static void StartBasicHapticEvent(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddTime(FlatBufferBuilder builder, float time) { builder.AddFloat(0, time, 0.0f); }
  public static void AddStrength(FlatBufferBuilder builder, float strength) { builder.AddFloat(1, strength, 0.0f); }
  public static void AddDuration(FlatBufferBuilder builder, float duration) { builder.AddFloat(2, duration, 0.0f); }
  public static void AddArea(FlatBufferBuilder builder, uint area) { builder.AddUint(3, area, 0); }
  public static void AddEffect(FlatBufferBuilder builder, StringOffset effectOffset) { builder.AddOffset(4, effectOffset.Value, 0); }
  public static Offset<BasicHapticEvent> EndBasicHapticEvent(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<BasicHapticEvent>(o);
  }
};


}
