// automatically generated by the FlatBuffers compiler, do not modify

namespace NullSpace.Communication
{

public enum PacketType : byte
{
 NONE = 0,
 SuitStatusUpdate = 1,
 TrackingUpdate = 2,
};


}
