// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_EXPERIENCE_NULLSPACE_HAPTICFILES_H_
#define FLATBUFFERS_GENERATED_EXPERIENCE_NULLSPACE_HAPTICFILES_H_

#include "flatbuffers/flatbuffers.h"

#include "HapticEffect_generated.h"
#include "HapticFrame_generated.h"
#include "HapticSample_generated.h"
#include "Pattern_generated.h"
#include "Sequence_generated.h"

namespace NullSpace {
namespace HapticFiles {

struct Experience;
struct ExperienceT;

struct ExperienceT : public flatbuffers::NativeTable {
  std::vector<std::unique_ptr<NullSpace::HapticFiles::HapticSampleT>> items;
};

struct Experience FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ITEMS = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<NullSpace::HapticFiles::HapticSample>> *items() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<NullSpace::HapticFiles::HapticSample>> *>(VT_ITEMS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_ITEMS) &&
           verifier.Verify(items()) &&
           verifier.VerifyVectorOfTables(items()) &&
           verifier.EndTable();
  }
  ExperienceT *UnPack(const flatbuffers::resolver_function_t *resolver = nullptr) const;
};

struct ExperienceBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_items(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<NullSpace::HapticFiles::HapticSample>>> items) { fbb_.AddOffset(Experience::VT_ITEMS, items); }
  ExperienceBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  ExperienceBuilder &operator=(const ExperienceBuilder &);
  flatbuffers::Offset<Experience> Finish() {
    auto o = flatbuffers::Offset<Experience>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<Experience> CreateExperience(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<NullSpace::HapticFiles::HapticSample>>> items = 0) {
  ExperienceBuilder builder_(_fbb);
  builder_.add_items(items);
  return builder_.Finish();
}

inline flatbuffers::Offset<Experience> CreateExperienceDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<NullSpace::HapticFiles::HapticSample>> *items = nullptr) {
  return CreateExperience(_fbb, items ? _fbb.CreateVector<flatbuffers::Offset<NullSpace::HapticFiles::HapticSample>>(*items) : 0);
}

inline flatbuffers::Offset<Experience> CreateExperience(flatbuffers::FlatBufferBuilder &_fbb, const ExperienceT *_o, const flatbuffers::rehasher_function_t *rehasher = nullptr);

inline ExperienceT *Experience::UnPack(const flatbuffers::resolver_function_t *resolver) const {
  (void)resolver;
  auto _o = new ExperienceT();
  { auto _e = items(); if (_e) { for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->items.push_back(std::unique_ptr<NullSpace::HapticFiles::HapticSampleT>(_e->Get(_i)->UnPack(resolver))); } } };
  return _o;
}

inline flatbuffers::Offset<Experience> CreateExperience(flatbuffers::FlatBufferBuilder &_fbb, const ExperienceT *_o, const flatbuffers::rehasher_function_t *rehasher) {
  (void)rehasher;
  return CreateExperience(_fbb,
    _o->items.size() ? _fbb.CreateVector<flatbuffers::Offset<HapticSample>>(_o->items.size(), [&](size_t i) { return CreateHapticSample(_fbb, _o->items[i].get(), rehasher); }) : 0);
}

inline const NullSpace::HapticFiles::Experience *GetExperience(const void *buf) {
  return flatbuffers::GetRoot<NullSpace::HapticFiles::Experience>(buf);
}

inline bool VerifyExperienceBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<NullSpace::HapticFiles::Experience>(nullptr);
}

inline void FinishExperienceBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<NullSpace::HapticFiles::Experience> root) {
  fbb.Finish(root);
}

inline std::unique_ptr<ExperienceT> UnPackExperience(const void *buf, const flatbuffers::resolver_function_t *resolver = nullptr) {
  return std::unique_ptr<ExperienceT>(GetExperience(buf)->UnPack(resolver));
}

}  // namespace HapticFiles
}  // namespace NullSpace

#endif  // FLATBUFFERS_GENERATED_EXPERIENCE_NULLSPACE_HAPTICFILES_H_
