// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_INSTRUCTIONS_NULLSPACE_CONFIGURATION_H_
#define FLATBUFFERS_GENERATED_INSTRUCTIONS_NULLSPACE_CONFIGURATION_H_

#include "flatbuffers/flatbuffers.h"

namespace NullSpace {
namespace Configuration {

struct Instruction;
struct InstructionT;

struct InstructionList;
struct InstructionListT;

struct InstructionT : public flatbuffers::NativeTable {
  std::string id;
  std::string name;
  std::string purpose;
  std::vector<std::string> parameters;
};

struct Instruction FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_NAME = 6,
    VT_PURPOSE = 8,
    VT_PARAMETERS = 10
  };
  const flatbuffers::String *id() const { return GetPointer<const flatbuffers::String *>(VT_ID); }
  const flatbuffers::String *name() const { return GetPointer<const flatbuffers::String *>(VT_NAME); }
  const flatbuffers::String *purpose() const { return GetPointer<const flatbuffers::String *>(VT_PURPOSE); }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *parameters() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_PARAMETERS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_ID) &&
           verifier.Verify(id()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_NAME) &&
           verifier.Verify(name()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_PURPOSE) &&
           verifier.Verify(purpose()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_PARAMETERS) &&
           verifier.Verify(parameters()) &&
           verifier.VerifyVectorOfStrings(parameters()) &&
           verifier.EndTable();
  }
  InstructionT *UnPack(const flatbuffers::resolver_function_t *resolver = nullptr) const;
};

struct InstructionBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(flatbuffers::Offset<flatbuffers::String> id) { fbb_.AddOffset(Instruction::VT_ID, id); }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) { fbb_.AddOffset(Instruction::VT_NAME, name); }
  void add_purpose(flatbuffers::Offset<flatbuffers::String> purpose) { fbb_.AddOffset(Instruction::VT_PURPOSE, purpose); }
  void add_parameters(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> parameters) { fbb_.AddOffset(Instruction::VT_PARAMETERS, parameters); }
  InstructionBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  InstructionBuilder &operator=(const InstructionBuilder &);
  flatbuffers::Offset<Instruction> Finish() {
    auto o = flatbuffers::Offset<Instruction>(fbb_.EndTable(start_, 4));
    return o;
  }
};

inline flatbuffers::Offset<Instruction> CreateInstruction(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> id = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> purpose = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> parameters = 0) {
  InstructionBuilder builder_(_fbb);
  builder_.add_parameters(parameters);
  builder_.add_purpose(purpose);
  builder_.add_name(name);
  builder_.add_id(id);
  return builder_.Finish();
}

inline flatbuffers::Offset<Instruction> CreateInstructionDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *name = nullptr,
    const char *purpose = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *parameters = nullptr) {
  return CreateInstruction(_fbb, id ? _fbb.CreateString(id) : 0, name ? _fbb.CreateString(name) : 0, purpose ? _fbb.CreateString(purpose) : 0, parameters ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*parameters) : 0);
}

inline flatbuffers::Offset<Instruction> CreateInstruction(flatbuffers::FlatBufferBuilder &_fbb, const InstructionT *_o, const flatbuffers::rehasher_function_t *rehasher = nullptr);

struct InstructionListT : public flatbuffers::NativeTable {
  std::vector<std::unique_ptr<InstructionT>> instructions;
};

struct InstructionList FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_INSTRUCTIONS = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<Instruction>> *instructions() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Instruction>> *>(VT_INSTRUCTIONS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_INSTRUCTIONS) &&
           verifier.Verify(instructions()) &&
           verifier.VerifyVectorOfTables(instructions()) &&
           verifier.EndTable();
  }
  InstructionListT *UnPack(const flatbuffers::resolver_function_t *resolver = nullptr) const;
};

struct InstructionListBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_instructions(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Instruction>>> instructions) { fbb_.AddOffset(InstructionList::VT_INSTRUCTIONS, instructions); }
  InstructionListBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  InstructionListBuilder &operator=(const InstructionListBuilder &);
  flatbuffers::Offset<InstructionList> Finish() {
    auto o = flatbuffers::Offset<InstructionList>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<InstructionList> CreateInstructionList(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Instruction>>> instructions = 0) {
  InstructionListBuilder builder_(_fbb);
  builder_.add_instructions(instructions);
  return builder_.Finish();
}

inline flatbuffers::Offset<InstructionList> CreateInstructionListDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<Instruction>> *instructions = nullptr) {
  return CreateInstructionList(_fbb, instructions ? _fbb.CreateVector<flatbuffers::Offset<Instruction>>(*instructions) : 0);
}

inline flatbuffers::Offset<InstructionList> CreateInstructionList(flatbuffers::FlatBufferBuilder &_fbb, const InstructionListT *_o, const flatbuffers::rehasher_function_t *rehasher = nullptr);

inline InstructionT *Instruction::UnPack(const flatbuffers::resolver_function_t *resolver) const {
  (void)resolver;
  auto _o = new InstructionT();
  { auto _e = id(); if (_e) _o->id = _e->str(); };
  { auto _e = name(); if (_e) _o->name = _e->str(); };
  { auto _e = purpose(); if (_e) _o->purpose = _e->str(); };
  { auto _e = parameters(); if (_e) { for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->parameters.push_back(_e->Get(_i)->str()); } } };
  return _o;
}

inline flatbuffers::Offset<Instruction> CreateInstruction(flatbuffers::FlatBufferBuilder &_fbb, const InstructionT *_o, const flatbuffers::rehasher_function_t *rehasher) {
  (void)rehasher;
  return CreateInstruction(_fbb,
    _o->id.size() ? _fbb.CreateString(_o->id) : 0,
    _o->name.size() ? _fbb.CreateString(_o->name) : 0,
    _o->purpose.size() ? _fbb.CreateString(_o->purpose) : 0,
    _o->parameters.size() ? _fbb.CreateVectorOfStrings(_o->parameters) : 0);
}

inline InstructionListT *InstructionList::UnPack(const flatbuffers::resolver_function_t *resolver) const {
  (void)resolver;
  auto _o = new InstructionListT();
  { auto _e = instructions(); if (_e) { for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->instructions.push_back(std::unique_ptr<InstructionT>(_e->Get(_i)->UnPack(resolver))); } } };
  return _o;
}

inline flatbuffers::Offset<InstructionList> CreateInstructionList(flatbuffers::FlatBufferBuilder &_fbb, const InstructionListT *_o, const flatbuffers::rehasher_function_t *rehasher) {
  (void)rehasher;
  return CreateInstructionList(_fbb,
    _o->instructions.size() ? _fbb.CreateVector<flatbuffers::Offset<Instruction>>(_o->instructions.size(), [&](size_t i) { return CreateInstruction(_fbb, _o->instructions[i].get(), rehasher); }) : 0);
}

inline const NullSpace::Configuration::InstructionList *GetInstructionList(const void *buf) {
  return flatbuffers::GetRoot<NullSpace::Configuration::InstructionList>(buf);
}

inline bool VerifyInstructionListBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<NullSpace::Configuration::InstructionList>(nullptr);
}

inline void FinishInstructionListBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<NullSpace::Configuration::InstructionList> root) {
  fbb.Finish(root);
}

inline std::unique_ptr<InstructionListT> UnPackInstructionList(const void *buf, const flatbuffers::resolver_function_t *resolver = nullptr) {
  return std::unique_ptr<InstructionListT>(GetInstructionList(buf)->UnPack(resolver));
}

}  // namespace Configuration
}  // namespace NullSpace

#endif  // FLATBUFFERS_GENERATED_INSTRUCTIONS_NULLSPACE_CONFIGURATION_H_
